version: '3.8'

services:
  function-app:
    build:
      context: .
      args:
        - DB_URL=jdbc:postgresql://localhost:5432/function_db
        - DB_URL_TEST=jdbc:postgresql://localhost:5432/function_db_test
    ports:
      - "8080:8080"
    expose:
      - "8080"
    secrets:
      - main.properties
    network_mode: host

secrets:
  main.properties:
    file: ./src/main/resources/secrets/main.properties